import Layout from "@/components/Layout";
import Header from "@/components/Header";
import HeroImage from "@/components/HeroImage";
import ContactForm from "@/components/ContactForm";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Header />
      <div>
        <Head>
          <title>Gonzalo Giudice DJ</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout>

          <HeroImage />
          <ContactForm />

        </Layout>
      </div>
    </>
  );
}
